### ISSUE TITLE
Feature proposal: forcing the query to be performed

### ISSUE THREAD

**Issue by UnrulyNatives** [dwightwatson/rememberable#1]
As in title, 
sometimes i need to overrule the remember() request - especially in the development process, when I want to test the chache behavior and judge if it is working as expected.

In other words: sometimes and in some of my templates I want to be 100% sure that I get fresh query, not chached.
ANother use is comparing two queries - cached and not-cached.

Thx.

**Comment by dwightwatson** [comment]
I can see the need for this, but perhaps it's better to change the caching mechanism at the framework level. For example, in development use the array cache driver instead of the file/redis driver as that will clear the cache every request. The alternative is to change the API or introduce a configuration file of some sort and I think that would jut make it more confusing. What do you think?

**Comment by UnrulyNatives** [comment]
It is too confusing to me, sorry. I am not that advanced. I am just giving an educated feedback.

Anyway, I will give you an example. Right now I use your package to get a list of c. 2000 authors in my personal quotation database. 
When I call in a form with these authors placed in a select input element (powered by select2.js)
I enable and disable the cache, but I see no  difference when generating a select in my view. I have no way to determine if the cache is working or not. 

Would https://github.com/barryvdh/laravel-debugbar be helpful in this?

**Comment by dwightwatson** [comment]
The cache leveraged is the one provided by Laravel. It's also worth noting that this package currently only worked with queries on Eloquent models.

You can use the debug bar, otherwise you can use `DB::enableQueryLog()` and then `DB::getQueryLog()` to see the queries that are run on any request. You should see that on your first request the query is run, but any subsequent requests the same database query is not performed (for example, you should see in the query log `SELECT * FROM authors LIMIT 2000` appear on the first request, but never again while it is cached).

You should check which cache driver you're currently using in your Laravel app - it defaults to the `file` system. If you set `CACHE_DRIVER` in your `.env` file to array the cache will only exist for one request and be cleared for each one.

Please let me know if this makes sense or not!

**Comment by alberto-bottarini** [comment]
A sort of `forceCacheRenew` method on the builder in order to ignore existing cache and to force regeneration.

An example could be

```php
$query = Model::longQuery();

if(Auth::isAdmin()) {
  $query->forceCacheRenew();
}

$data = $query->get();

```
