### ISSUE TITLE
Setting custom cache key results in empty cache file

### ISSUE THREAD

**Issue by digixweb** [dwightwatson/rememberable#12]
https://github.com/digixweb/test.git

I am using this on most recent Laravel on homestead.

Reloading the /test page results in representation of the empty cache file.

**Comment by dwightwatson** [comment]
Okay, I think I know what is going on here. Calling the pagination functions actually performs two queries - one to get the count of the resource to build the pagination links, and the other to get the resources to be displayed on a given page. Using a custom cache key is then being used for both of these queries and so the contents of the cache after using the `paginate()` method is the custom cache key with the total count of the resource.

It works when not using a custom cache key because the cache key is generated for each of the two queries, so the responses are stored separately from each other.

Unfortunately this would be quite a bit of extra work to implement, we'd need to override the pagination functions entirely and accept two custom cache keys. It also means there is a higher potential for this package to break when Laravel makes changes to the ORM upstream. At this stage, I don't think it is within the scope of this package to make custom cache keys work with pagination.

I'm sorry it took so long to get to the bottom of this, it was very hard to understand what you were getting at with just code snippets before. My recommendation would simply be to avoid using custom cache keys when paginating records, otherwise if it is a must then you can use the `Cache` facade to wrap your query up with a key that way.
