### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by isbkch** [dwightwatson/rememberable#13]
Am I the only one getting this error ?

```
BadMethodCallException in Builder.php line 2071:
Call to undefined method Watson\Rememberable\Query\Builder::getQuery()
```

I installed it using the abstract class as mentioned in the docs, but the first time I try to use any model, I got the error above.

**Comment by dwightwatson** [comment]
I've not seen that before, and there's nothing from this package calling `getQuery()`. What code have you used that is causing this error? Are you using any other packages that might impact how Eloquent works?

**Comment by dwightwatson** [comment]
Closing as no more details have been provided.

**Comment by santiagazo** [comment]
I am getting this error too. I know you closed this but I am unsure as to how I can fix this. 

Call to undefined method Watson\Rememberable\Query\Builder::untag()

Using L5.2 I have a Model extending Eloquent where I am placing - use Rememberable; This (per my understanding allows me to make a sweeping change so that rememberable is available to all my models that are extending Model.php). When I am using another package for rtConners/Tag package, I am having and issue when deleting the tags. I got it to work for just fine for placing the tags but something on deleting them has caused it to throw this errror. Any ideas?

**Comment by dwightwatson** [comment]
I'd suggest that you haven't set the tag package up right (unless the tag package also overrides the query builder, in which case there could be an incompatibility, but I doubt it would). Usually when I see this sort of thing it's because I didn't define the relationship on the model properly. You ignore the fact it's calling on the package query builder and instead look at your model. Ensure it has an untag() method where it's meant to be.
