### ISSUE TITLE
Multiple cache tags?

### ISSUE THREAD

**Issue by ghost** [dwightwatson/rememberable#30]
Is there a way to set multiple cache tags for a query? (Sorry, first time doing something like this.)
If not, is there a way to flush tags using regular expressions? (e.g. flush all tags with "user:1")
Thank you for this BTW! Was looking for remember() and was not disappointed.

**Comment by dwightwatson** [comment]
I've not tested it because I don't use cache tags myself, but you should be able to set the cache tags as an array as you would normally in Laravel. Something like `User::cacheTags(['users', 'whatever'])->remember(5)->get()`. 

Also, not aware of any way to flush tags using regular expressions - I suspect that functionality would only be available in certain engines and I'm not aware of Laravel having implemented it on any driver (we use Laravel's cache driver under-the-hood).

Thanks, I'm glad it's been of use! Please let me know if you have any other questions.

**Comment by ghost** [comment]
Oh, guess I can live with that, it's more than enough for me. Will report if the arrays don't work as expected.
One more thing, can I call the `remember()` and `cacheTags()` after functions such as `get()` and `all()`?
Thank you for responding!

**Comment by dwightwatson** [comment]
No - you'll need to call them before that, as they're on the query builder. The second you call `get()` or `all()` the query is performed and the results are returned instead - it'll be too late to cache the query and you'll be calling those functions on your result set instead. Hope this helps!

**Comment by ghost** [comment]
I'm assuming `flushCache()` accepts an array as well, right? Might be worth updating the docs if so.
Yes, it certainly does. Thank you!
