### ISSUE TITLE
Flush remember cache feature

### ISSUE THREAD

**Issue by indesignlatam** [dwightwatson/rememberable#5]
It wil be a nice add to make a method to flush the cached querys

**Comment by dwightwatson** [comment]
Because we use the Laravel cache implementation we don't really have the ability to do this. In a development environment you can change your cache driver to `file` (and empty the cache directory) or use `array` and it will be cleared after every request. It would be a lot harder to flush the queries in other drivers, we'd need to actually record which queries have been cached as well in order to flush them out. Maybe something for the future, but not for now I'm afraid.

**Comment by Kovah** [comment]
First of all thank you for this awesome package. Managed to get from 44 queries to zero with it.
I have an idea for the flushing: wouldn't it be possible to use cache tags for this?

Let's say you add the cache tag `user_queries` to any user related query as mentioned in #16.
Wouldn't it be possible to use `Cache::tags('user_queries')->flush();` to delete all cached queries with the tag?

---

**Edit**: Yes, this works! I added a cache tag to a query, reloaded the page and the query count became zero. After adding `Cache::tags('user_queries')->flush();` before the query and reloading the page, Laravel fires up the SQL queries again. 🎉 

Even if it requires adding cache tags this is a suitable solution for flushing cached queries. Maybe the documentation should be updated with this hint.
