### ISSUE TITLE
sha256 hash

### ISSUE THREAD

**Issue by hondnl** [dwightwatson/rememberable#60]
Thanks for your script !

Is there a specific reason you chose to use the quite slow sha256 hash to create the cache keys?

There are very nice and a lot faster hashes you could use. Security is not important , since it is is internal.

Cheers,
Paolo

**Comment by dwightwatson** [comment]
Version 1.0 used MD5 and in version 2.0 we switched to SHA256 by suggestion.

MD5 was more likely to have a collision than SHA256 and security actually is a concern. If you cached a query that was specific for a particular user and ended up serving it to someone else because of a hash collision then you've breached that user's privacy.

Also, SHA256 is only marginally slower than MD5. The difference in your app really shouldn't be noticeable. It was decided that this trade-off was worth it for better security.

If MD5 is that important to you feel free to use ~1.0 but it is no longer maintained.

**Comment by hondnl** [comment]
Thank you for the explanation.  I decided to use http://cyan4973.github.io/xxHash/   
It is collision secure and very fast.
It will need an PHP extension tho.. But I think php is in the middle of implementing it in it's core.
So keep a look-out for future builds ;)
