### ISSUE TITLE
Cache the query for the current request

### ISSUE THREAD

**Issue by AdrienPoupa** [dwightwatson/rememberable#73]
Hello,

I would like to know if there is a simple way to remember the results for the current request. This would avoid having duplicated queries for the same page request but avoid any side effect that caching can have.

Maybe using the array cache driver would have this effect?

Is it something that your package supports?

**Comment by dwightwatson** [comment]
I believe you can specify the cache driver on your model or as part of the request using [`cacheDriver('array'`)](https://github.com/dwightwatson/rememberable/blob/master/src/Query/Builder.php#L150-L161). That should give you the flexibility to have an entire model or specific queries go into an in-memory cache rather than your main app cache. Let me know if that solution doesn't work out for you

**Comment by AdrienPoupa** [comment]
Thank you!
